insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_22',5.0122,'5.oa.a.1','f(d(b(a)c)e)g');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_21',5.0121,'5.oa.a.1','((b(a)c)d)e');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_20',5.0120,'5.oa.a.1',' e((b(a)c)d)');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_19',5.0119,'5.oa.a.1','(d(b(a)c))e');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_18',5.0118,'5.oa.a.1','e(d(b(a)c))');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_17',5.0117,'5.oa.a.1','d(b(a)c)e');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_16',5.0116,'5.oa.a.1','d(b(a)c)');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_15',5.0115,'5.oa.a.1',' c(b(a))');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_14',5.0114,'5.oa.a.1','c((a)b)d');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_13',5.0113,'5.oa.a.1','(c(a)b)d');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_12',5.0112,'5.oa.a.1','((a)b)c');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_11',5.0111,'5.oa.a.1','c(a)d(b)e');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_10',5.0110,'5.oa.a.1','c(a)(b)d');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_9',5.0109,'5.oa.a.1','(a)c(b)d');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_8',5.0108,'5.oa.a.1','c(a)d(b)');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_7',5.0107,'5.oa.a.1','c(a)(b)');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_6',5.0106,'5.oa.a.1','c(a)(b)');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_5',5.0105,'5.oa.a.1','c(a)(b)');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_4',5.0104,'5.oa.a.1','(a)(b)');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_3',5.0103,'5.oa.a.1','b(a)c');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_2',5.0102,'5.oa.a.1','(a)b');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.1_1',5.0101,'5.oa.a.1','b(a)');
insert into item_types(id,progression,core_standards_id,description) values ('k.nbt.a.1_1',4.502,'k.nbt.a.1','Pick out what equation containing 10 is equal to number.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.2_4',4.204,'k.oa.a.2','Subtraction word problems within 10.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.2_3',4.203,'k.oa.a.2','Addition word problems within 10.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.2_2',4.202,'k.oa.a.2','Subtract within 10.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.2_1',4.201,'k.oa.a.2','Add within 10.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_1',0.0201,'k.cc.a.2','This type will ask what 2 numbers come next after a number from 0-99.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_2',0.0202,'k.cc.a.2','This type will ask what 3 numbers come next after a number from 0-99.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_3',0.0203,'k.cc.a.2','This type will ask what the missing number is. e.g. What is the missing number? 1,2,3,_,5,6,7. This will be done up to 100.');
        insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_4',0.0204,'k.cc.a.2','What comes next after a number from 0-10 that does not end in 0 or 9.');
        insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_5',0.0205,'k.cc.a.2','What comes next after a number from 11-99 that does not end in 0 or 9.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_6',0.0206,'k.cc.a.2','What comes next after 9.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_7',0.0207,'k.cc.a.2','What comes next after a number ending in 9 from 11-99.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_8',0.0208,'k.cc.a.2','What comes next after zero.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_9',0.0209,'k.cc.a.2','What comes next after 10.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.2_10',0.0210,'k.cc.a.2','What comes next after number ending in zero from 11-99.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.4_1',4.401,'k.oa.a.4','');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_13',5.0213,'5.oa.a.2','Write expression based on word problem. Words: more than, times that many');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_12',5.0212,'5.oa.a.2','Write expression based on word problem. Words: divided, subtracted');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_11',5.0211,'5.oa.a.2','Write expression based on word problem. Words: divided, subtracted ');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_10',5.0210,'5.oa.a.2','');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_6',5.0206,'5.oa.a.2','Write expression based off sentence expression. Words used: product of , seven less.');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_5',5.0205,'5.oa.a.2','Write expression based off sentence expression. Words used: product of , seven less.');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_4',5.0204,'5.oa.a.2','Write expression based off sentence expression. Words used: product of , seven less.');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_3',5.0203,'5.oa.a.2','Write expression based off sentence expression. Words used: difference, times .');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_2',5.0202,'5.oa.a.2','Write expression based off sentence expression. Words used: times, sum.');
insert into item_types(id,progression,core_standards_id,description) values ('5.oa.a.2_1',5.0201,'5.oa.a.2','Write expression based off sentence expression. Words used add, multiply.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.c.6_1',3.101,'k.cc.c.6','Compare 10 objects with greater than.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.c.6_2',3.102,'k.cc.c.6','Compare 10 objects with equal to.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.c.6_3',3.103,'k.cc.c.6','Compare 10 objects with less than.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.b.5_4',2.04,'k.cc.b.5','Count the objects up to 10 in scattered pattern.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.b.5_3',2.03,'k.cc.b.5','Count the objects up to 20 in a circle.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.b.5_2',2.02,'k.cc.b.5','Count the objects up to 20 in a line.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.b.5_1',2.01,'k.cc.b.5','Count the objects up to 20 in a rectangular array.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.a.1_1',1.0101,'k.cc.a.1','What comes next when counting by ten from numbers that end in zero from 10 to 100.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.c.7_1',3.201,'k.cc.c.7','Compare 2 numbers with greater than.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.c.7_2',3.202,'k.cc.c.7','Compare 2 numbers with equal to.');
insert into item_types(id,progression,core_standards_id,description) values ('k.cc.c.7_3',3.203,'k.cc.c.7','Compare 2 numbers with less than.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.5_2',4.502,'k.oa.a.5','Subtract within 5.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.5_1',4.501,'k.oa.a.5','Add within 5.');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_1',4.0601,'4.nbt.a.1','This type will ask which digit is in the ones column');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_2',4.0602,'4.nbt.a.1','This type will ask which digit is in the tens column');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_3',4.0603,'4.nbt.a.1','This type will ask which digit is in the hundreds column');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_4',4.0604,'4.nbt.a.1','This type will ask which digit is in the thousands column');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_5',4.0605,'4.nbt.a.1','This type will give thousands and ask for hundreds');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_6',4.0606,'4.nbt.a.1','This type will give thousands and ask for tens');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_7',4.0607,'4.nbt.a.1','This type will give thousands and ask for ones');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_8',4.0608,'4.nbt.a.1','This type will give hundreds and ask for tens');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_9',4.0609,'4.nbt.a.1','This type will give hundreds and ask for ones');
insert into item_types(id,progression,core_standards_id,description) values ('4.nbt.a.1_10',4.0610,'4.nbt.a.1','This type will give tens and ask for ones');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.1_1',4.101,'k.oa.a.1','Add within 5 with pictures to help.');
insert into item_types(id,progression,core_standards_id,description) values ('k.oa.a.1_2',4.102,'k.oa.a.1','Subtract within 5 with pictures to help');
