ALTER TABLE schools ADD city text;
ALTER TABLE schools ADD state text;
ALTER TABLE schools ADD zip text;
delete from schools where id > 2;
update schools set city = 'Philadelphia' where id = 2; 
update schools set state = 'Pennsylvannia' where id = 2; 
update schools set state = '19125' where id = 2; 
update schools set city = 'Philadelphia' where id = 1; 
update schools set state = 'Pennsylvannia' where id = 1; 
update schools set state = '19125' where id = 1; 
