insert into evaluations (id,description) values (19,'The Super Izzy');
alter table users add alltimesuperizzy integer;
insert into evaluations (id,description) values (20,'Basic Skills Fourth');
alter table users add alltimebasicskillsfourth integer;
insert into evaluations (id,description) values (21,'Basic Skills Fifth');
alter table users add alltimebasicskillsfifth integer;
update evaluations set description = 'Basic Skills 5th' where id = 21;
insert into evaluations (id,description) values (22,'Basic Skills Third');
alter table users add alltimebasicskillsthird integer;
update evaluations set description = 'Basic Skills 3rd' where id = 22;
insert into evaluations (id,description) values (23,'Basic Skills Second');
alter table users add alltimebasicskillssecond integer;
update evaluations set description = 'Basic Skills 2nd' where id = 23;
insert into evaluations (id,description) values (24,'Basic Skills First');
alter table users add alltimebasicskillsfirst integer;
update evaluations set description = 'Basic Skills 1st' where id = 24;
insert into evaluations (id,description) values (25,'Basic Skills Kindergarten');
alter table users add alltimebasicskillskindergarten integer;
update evaluations set description = 'Basic Skills K' where id = 25;
insert into evaluations (id,description) values (26,'Make Ten');
alter table users add alltimemaketen integer;
update evaluations set description = 'Make Ten' where id = 26;
insert into evaluations (id,description) values (27,'Add Subtract Within 10');
alter table users add alltimeaddsubtractwithinten integer;
update evaluations set description = 'Add subtract within 10' where id = 27;
insert into evaluations (id,description) values (28,'Add Subtract Within 20');
alter table users add alltimeaddsubtractwithintwenty integer;
update evaluations set description = 'Add subtract within 20' where id = 28;
